#!/usr/bin/env python 

"""
This check is designed purely for testing. 
It simulates a check failure/success.
"""

import sys
from argparse import ArgumentParser


if __name__ == "__main__":
    parser = ArgumentParser(description='Designed for testing. Will exit with 1'
                            ' unless you pass the -s option.')
    parser.add_argument('-s', '--succeed', action='store_true', required=False, 
                        help='Return success.')
    args = parser.parse_args()
    
    if args.succeed:
        print ('Exiting with 0 (success).')
        sys.exit(0)
    else:
        print ('Exiting with 1 (failure).')
        sys.exit(1) 
