#ifndef STRICT_WARNINGS_ON_H
#define STRICT_WARNINGS_ON_H

#pragma GCC diagnostic push
#pragma GCC diagnostic error "-Wunused-local-typedefs"
//#pragma GCC diagnostic error "-Wno-deprecated-declarations"
#pragma GCC diagnostic error "-Waddress"
#pragma GCC diagnostic error "-Warray-bounds"
#pragma GCC diagnostic error "-Wc++11-compat"
#pragma GCC diagnostic error "-Wchar-subscripts"
#pragma GCC diagnostic error "-Wclobbered"
#pragma GCC diagnostic error "-Wcomment"
// This is useful for flagging uninitialized members, but lots of boost errors
// #pragma GCC diagnostic error "-Weffc++"
#pragma GCC diagnostic error "-Wconversion"
#pragma GCC diagnostic error "-Wsign-conversion"
#pragma GCC diagnostic error "-Wempty-body"
#pragma GCC diagnostic error "-Werror-qualifiers"
#pragma GCC diagnostic error "-Wenum-compare"
#pragma GCC diagnostic error "-Wformat"
#pragma GCC diagnostic error "-Wmain"
#pragma GCC diagnostic error "-Wmaybe-uninitialized"
#pragma GCC diagnostic error "-Wmissing-braces"
#pragma GCC diagnostic error "-Wmissing-field-initializers"
#pragma GCC diagnostic error "-Wnonnull"
#pragma GCC diagnostic error "-Wparentheses"
// #pragma GCC diagnostic error "-Wreorder"
#pragma GCC diagnostic error "-Wreturn-type"
#pragma GCC diagnostic error "-Wsequence-point"
// #pragma GCC diagnostic error "-Wsign-compare"
#pragma GCC diagnostic error "-Wstrict-aliasing"
#pragma GCC diagnostic error "-Wstrict-overflow"
#pragma GCC diagnostic error "-Wswitch"
#pragma GCC diagnostic error "-Wtrigraphs"
#pragma GCC diagnostic error "-Wuninitialized"
// #pragma GCC diagnostic error "-Wunknown-pragmas"
#pragma GCC diagnostic error "-Wunused-function"
#pragma GCC diagnostic error "-Wunused-label"
#pragma GCC diagnostic error "-Wunused-value"
#pragma GCC diagnostic error "-Wunused-variable"
// #pragma GCC diagnostic error "-Wunused-parameter"
#pragma GCC diagnostic error "-Wunused-but-set-parameter"
#pragma GCC diagnostic error "-Wvolatile-register-var"
#pragma GCC diagnostic error "-Wtype-limits"

#endif
